pipeline {
         agent any
         stages {
                stage ("build1") {
                         steps {
                         echo "this is from git poll scm " 
                              } 
                                  }  
                 }  
}
